// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQcd7c3DFkipWNaPaFt23jvDydaZyGCJI',
    appId: '1:674245761277:web:cc5d64e012697c86f24694',
    messagingSenderId: '674245761277',
    projectId: 'nihat-application',
    authDomain: 'nihat-application.firebaseapp.com',
    storageBucket: 'nihat-application.appspot.com',
    measurementId: 'G-YMXTPL4SN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOTJb7NghYlzMhea7v0JSMj3A9GEA8Zis',
    appId: '1:674245761277:android:85877007046c82f5f24694',
    messagingSenderId: '674245761277',
    projectId: 'nihat-application',
    storageBucket: 'nihat-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYganVm5VkHo7_DOvQbFqokqcmz1Axt54',
    appId: '1:674245761277:ios:7ac11f3b33972355f24694',
    messagingSenderId: '674245761277',
    projectId: 'nihat-application',
    storageBucket: 'nihat-application.appspot.com',
    iosBundleId: 'com.example.flutterMarch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYganVm5VkHo7_DOvQbFqokqcmz1Axt54',
    appId: '1:674245761277:ios:66fcd3012f9414bcf24694',
    messagingSenderId: '674245761277',
    projectId: 'nihat-application',
    storageBucket: 'nihat-application.appspot.com',
    iosBundleId: 'com.example.flutterMarch.RunnerTests',
  );
}
